### ISSUE TITLE
Npm Install Error

### ISSUE THREAD

**Issue by houyongkuo** [Linkurious/ogma-vue#52]
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @linkurious/ogma-vue@1.0.1
npm WARN Found: @linkurious/ogma@undefined
npm WARN node_modules/@linkurious/ogma
npm WARN   peer @linkurious/ogma@">=4.6.6" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @linkurious/ogma@">=4.6.6" from the root project
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@linkurious%2fogma - Not found
npm ERR! 404 
npm ERR! 404  '@linkurious/ogma@>=4.6.6' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by w8r** [comment]
Hi! Ogma is a commercial library, do you have an API key?
